### ISSUE TITLE
Model open/sync data missing in project health report

### ISSUE THREAD

**Issue by zhukoven** [HOKGroup/MissionControl#252]
I don't know whether this is an angular.js app problem or not, but we are missing open/sync data in project health report. Google throws a bunch of errors with 404 and "A negative value is not valid" (see the screenshot attached).
![image](https://user-images.githubusercontent.com/27201628/49500214-35b00d80-f881-11e8-9ff4-5ed4afc43999.png)

The weird thing is that MongDB shows the data that we need:
![image](https://user-images.githubusercontent.com/27201628/49500330-87589800-f881-11e8-9c10-9aa820e97d6f.png)

Are we missing something?

**Comment by djsiroky** [comment]
Hi @zhukoven, the errors shown seem to be related to the warnings API call to `/api/v2/warnings/centralpath/:uri` section more than the model section, but that may also be an issue as well. Can you go to the Chrome DevTools Network tab and reload the page. That way we can see if the model section is also having issues. For example: 

![IMG](https://duaw26jehqd4r.cloudfront.net/items/3l2o1H3j3K3a1m0I3D26/%5B8a2fe16eb1f6879fe1ee06dfe5ed3fb1%5D_Screenshot-2018-12-06T15%253A32%253A04.692Z.png?X-CloudApp-Visitor-Id=3216555&v=8184e075)

**Comment by ksobon** [comment]
You need at least Mongo 3.6 installed.

**Comment by zhukoven** [comment]
@ksobon maybe our Mongo is too fresh, or we're missing some plugins?

mongod --version
db version v4.0.4
git version: f288a3bdf201007f3693c58e140056adf8b04839
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
allocator: tcmalloc
modules: none
build environment:
    distmod: ubuntu1804
    distarch: x86_64
    target_arch: x86_64

**Comment by ksobon** [comment]
Can you install 3.6? Let us know if that solves it.

**Comment by zhukoven** [comment]
Well, the issue is still there with 3.6:
mongod --version
db version v3.6.9
git version: 167861a164723168adfaaa866f310cb94010428f
OpenSSL version: OpenSSL 1.0.2n  7 Dec 2017
allocator: tcmalloc
modules: none
build environment:
    distmod: ubuntu1604
    distarch: x86_64
    target_arch: x86_64

![image](https://user-images.githubusercontent.com/27201628/49651978-c897a600-fa41-11e8-9417-6d2f11888fff.png)

**Comment by ksobon** [comment]
Just as a general comment the model stats data doesn't aggregate until there are at least 2 synchs and 2 open events stored in the DB. That's because all of the charts we show are line charts that need at least two data points. So basically verify in your DB that you have at least two items for onsynched, onopened. I saw in your previous images that you have plenty of open events logged, but just check that you also have synch events.

**Comment by zhukoven** [comment]
Yes, I have a bunch of open and sync events, but the data doesn't come to the frontend. I also noticed an error in the Project page (in all of my test projects @ MissionControl):
![image](https://user-images.githubusercontent.com/27201628/49655256-3c8a7c00-fa4b-11e8-8b31-40a517962874.png)

**Comment by djsiroky** [comment]
Well, I thought it might've been a Windows vs Ubuntu issue (we're developing + deploying on Windows), but I was just able to deploy an Ubuntu machine with the same seed data I use for development and I'm not running in to the same issues. I'm not getting any `500 (Internal Server Error)` responses.

Which specific API calls are returning the `"Unrecognized pipeline stage name: '$facet'"` error?

**Comment by zhukoven** [comment]
We made a clean install with Mongo 3.6.9 and now it works. Seems that the problem was related to the junk left by Mongo 4.
@djsiroky, @ksobon, thanks for your help, guys!
