### ISSUE TITLE
Unable to upload other models in MC

### ISSUE THREAD

**Issue by albertotono** [HOKGroup/MissionControl#255]
I set up several models that are in the HOK SF Server in Mission Control, but I am not able to retrieve these data. It always appears "No Data Available". In one example (4th and Harrison) I see that in the configurations when I try to add a Revit file, it points me to another path (like in the 2018 version instead of 2019).
![mission control](https://user-images.githubusercontent.com/11828200/52732196-78265280-2f74-11e9-8043-7c748e28d6c3.png)
and the 2019 version is also empty
![image](https://user-images.githubusercontent.com/11828200/52732293-b15ec280-2f74-11e9-9431-aace90bc2d87.png)

)

**Comment by djsiroky** [comment]
Hi @albertotono,

I just took a quick look at this project and under the only configuration it appeared that none of the monitors were turned on. I just turned on the Health Monitor which *should* populate the data in MC. You may want to look through and turn on any other monitors that may be of interest to you and the project team.

**Comment by djsiroky** [comment]
I just checked the model in MC and it looks like the health report data is being populated. Closing this, but let me know if a different issue comes up about this particular project.
